# Generated by Django 3.2.4 on 2021-06-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiacar', '0003_auto_20210624_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='price_predelay',
        ),
        migrations.AddField(
            model_name='rental',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
    ]
