# Generated by Django 3.2.4 on 2021-06-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiacar', '0004_auto_20210624_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='time_returned',
            field=models.DateTimeField(null=True),
        ),
    ]
