# Generated by Django 3.2.4 on 2021-06-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiacar', '0005_alter_rental_time_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='price_total',
            field=models.FloatField(null=True),
        ),
    ]
