# Generated by Django 3.2.4 on 2021-06-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiacar', '0006_alter_rental_price_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='available',
            new_name='_available',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='_available',
            field=models.BooleanField(db_column='available', default=True),
        ),
    ]
