# Generated by Django 3.2.4 on 2021-06-24 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asiacar', '0007_auto_20210624_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='_available',
            new_name='available',
        ),
    ]
