# Generated by Django 3.2.4 on 2021-06-25 00:06

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('asiacar', '0008_rename__available_vehicle_available'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rental',
            constraint=models.CheckConstraint(check=models.Q(('time_end__gt', django.db.models.expressions.F('time_start'))), name='time_end constraint'),
        ),
    ]
