# Generated by Django 3.2.4 on 2021-06-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiacar', '0009_rental_time_end constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(choices=[(50.0, '50 euro'), (20.0, '20 euro'), (10.0, '10 euro'), (5.0, '5 euro'), (2.0, '2 euro'), (1.0, '1 euro'), (0.5, '50 cent'), (0.2, '20 cent')])),
                ('name', models.CharField(max_length=30, unique=True)),
                ('number', models.IntegerField()),
            ],
        ),
    ]
